name: Auto Pull Request and Info
#현정 내가 이 yml이 무슨 장치인지 확실히는 모르겠는데
#자동으로 한다는 거가 리포 주인일 때 하려는 건가 싶어서 일단은 주인 리포인지 확인해서 맞을 때 진행하도록 수정했어
#편하게 다시 수정해도 돼

on:
  push:
    branches:
      - '*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
#sc가 추가로 넣음
    - name: Check if pusher is the repository owner
      id: is_owner
      run: echo "::set-output name=is_owner::${{ github.actor == github.repository_owner }}"  
#여기까지
    - name: Set environment variables
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        USER_NAME=$GITHUB_ACTOR
        ORIGIN_BRANCH=$BRANCH_NAME
        DESTINATION_BRANCH=main
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV
        echo "ORIGIN_BRANCH=$ORIGIN_BRANCH" >> $GITHUB_ENV
        echo "DESTINATION_BRANCH=$DESTINATION_BRANCH" >> $GITHUB_ENV
      shell: bash

    - name: Create Pull Request
      run: |
        echo "Creating Pull Request from $BRANCH_NAME to $DESTINATION_BRANCH"
        response=$(curl -X POST \
                    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    -d "{\"title\": \"Automated Pull Request\", \"head\": \"$BRANCH_NAME\", \"base\": \"$DESTINATION_BRANCH\"}" \
                    "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls")
        echo "Response: $response"

    - name: Display Environment Variables
      run: |
        echo "User: $USER_NAME"
        echo "From Branch: $ORIGIN_BRANCH"
        echo "To Branch: $DESTINATION_BRANCH"

        echo "BRANCH_NAME=$BRANCH_NAME"
        echo "USER_NAME=$USER_NAME"
        echo "ORIGIN_BRANCH=$ORIGIN_BRANCH"
        echo "DESTINATION_BRANCH=$DESTINATION_BRANCH"

  
    - name: Run kakaotalkAlarm.py
      #if sc가 집어넣음
      if: steps.is_owner.outputs.is_owner == 'true'
      run: python .github/workflows/sendToMeAlarm.py
      #run: python .github/workflows/kakaotalkAlarm.py
