name: Simple Action

on:
  push:
    branches:
      - '*'

jobs:
  simple-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Print a message
      run: echo "Hello, this is a simple GitHub Action!"
