name: Update User Profile

on:
  push:
    branches:
      - sc-4th-practice  # 원하는 브랜치로 변경
permissions:
  contents: write
jobs:
  update_profile:
    runs-on: ubuntu-latest  # 원하는 실행 환경으로 변경

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set User Information
        id: user_info
        run: |
          USER_NAME=$(git log -1 --pretty=format:'%an')
          COMMIT_TIME=$(git log -1 --pretty=format:'%ci')
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          echo "::set-output name=user_name::$USER_NAME"
          echo "::set-output name=commit_time::$COMMIT_TIME"
          echo "::set-output name=commit_message::$COMMIT_MESSAGE"

      - name: Update Markdown File
        run: |
          echo "## User Profile" > profile.md
          echo "- User ID or Nickname: ${{ steps.user_info.outputs.user_name }}" >> profile.md
          echo "- Commit Time: ${{ steps.user_info.outputs.commit_time }}" >> profile.md
          echo "- Commit Message: ${{ steps.user_info.outputs.commit_message }}" >> profile.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add profile.md
          git commit -m "Update user profile"
          git push
