name: Update User Profile

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - sc-4th-practice  # 원하는 브랜치로 변경
permissions:
  contents: write
jobs:
  update_profile:
    runs-on: ubuntu-latest  # 원하는 실행 환경으로 변경

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run kakaotalkAlarm.py
        run: python .github/workflows/kakaotalkAlarm.py

      - name: Set User Information
        id: user_info
        run: |
          USER_NAME=$(git log -1 --pretty=format:'%an')
          COMMIT_TIME=$(git log -1 --pretty=format:'%ci')
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          echo "::set-output name=user_name::$USER_NAME"
          echo "::set-output name=commit_time::$COMMIT_TIME"
          echo "::set-output name=commit_message::$COMMIT_MESSAGE"

      - name: Read Existing Profile Content
        id: read_existing
        run: |
          if [ -f "profile.md" ]; then
            EXISTING_CONTENT=$(cat profile.md)
            echo "::set-output name=existing_content::$EXISTING_CONTENT"
          else
            echo "::set-output name=existing_content::"
          fi

      - name: Update Markdown File
        run: |
          echo "::set-output name=new_content::" >> profile.md
          echo "## User Profile" >> profile.md
          echo "- User ID or Nickname: ${{ steps.user_info.outputs.user_name }}" >> profile.md
          echo "- Commit Time: ${{ steps.user_info.outputs.commit_time }}" >> profile.md
          echo "- Commit Message: ${{ steps.user_info.outputs.commit_message }}" >> profile.md
          echo "" >> profile.md
          echo "${{ steps.read_existing.outputs.existing_content }}" >> profile.md
          echo "${{ steps.new_content.outputs.new_content }}" >> profile.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add profile.md
          git commit -m "Update user profile"
          git push
