name: 파이썬코드변수저장되나요

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Environment Variable
      run: echo "MY_ENV_VAR=hihi" >> $GITHUB_ENV

    - name: Run Python Script
      run: python .github/workflows/my_script.py
